### ISSUE TITLE
Python CLI Test

### ISSUE THREAD

**Issue by jpitts** [designforsf/brigade-matchmaker#1]
Python script to test out the sorting algorithm.

Input:
- user
  - email
  - interests: comma delimited keywords
  - skills: comma delimited  keywords
  - role: comma delimited  keywords

Database (initially simulated):
- groups, each having:
  - interests: array of { keyword, weight }
  - skills needed: array of { keyword, weight }
  - roles needed:  array of { keyword, weight }

Output:
- sorted list of groups

**Comment by knowsuchagency** [comment]
I've begun the process of documenting the data model in the notebook on my branch. 

[link](https://github.com/designforsf/brigade-matchmaker/blob/stephan-dev/components/algorithm/notebooks/schema_algorithm_api.ipynb)

**Comment by jpitts** [comment]
First steps toward getting this to work.

SEE: https://github.com/designforsf/brigade-matchmaker/blob/0a9fe2905b5761842babbe16e52c8b35c74b0869/components/algorithms/match-algo.py

**Comment by jpitts** [comment]
This is complete.
