### ISSUE TITLE
Convert Taxonomy Selector to Flexbox

### ISSUE THREAD

**Issue by jpitts** [designforsf/brigade-matchmaker#32]

**Comment by alschmiedt** [comment]
Here is a demo of what flexbox can do : https://codepen.io/anon/pen/eezJaJ

**Comment by jpitts** [comment]
Use the same data structure currently used for UI rendering in [taxonomy-selector.js](https://github.com/designforsf/brigade-matchmaker/blob/9e28eafd56ed5e9242375e1514810d2612ace4d6/components/taxonomy-selector/public/js/project-match/taxonomy-selector.js).

https://github.com/designforsf/brigade-matchmaker/blob/master/docs/taxonomy.md#tree-structure-for-ui-rendering
