### ISSUE TITLE
Messaging: Selection tags should match the messaging form attachment tags

### ISSUE THREAD

**Issue by jpitts** [designforsf/brigade-matchmaker#50]
To recreate:

1. User selects a tag for skill / interest / learn skill (e.g. HTML)
2. In the top project, user clicks "Contact Project Lead"
3. In the minmaximized messaging form, these tags do not match the tags in the messaging form attachment. In the messaging form, the tags shoe the hierarchy as opposed to the title.

![image](https://user-images.githubusercontent.com/509756/41071647-fb9e9c40-69ad-11e8-92f1-638fc2c9e554.png)

**Comment by pauljickling** [comment]
Fixed in the update I just pushed to dev (9/3/2018)
