### ISSUE TITLE
"MessagingView is not defined" error when clicking "Contact Project Lead"

### ISSUE THREAD

**Issue by tsell** [designforsf/brigade-matchmaker#77]
Steps to reproduce:
1. Go through installation.md and get a freshly-installed-from-HEAD installation
2. Go to localhost:5465 to load the UI
3. Generate some matches
4. Click "Contact Project Lead"
5. Open JS console and see the error:

```
 ProjectView.js:18 Uncaught ReferenceError: MessagingView is not defined
     at child.popUpMessage (ProjectView.js:18)
     at HTMLDivElement.dispatch (jquery.js:3332)
     at HTMLDivElement.eventHandle (jquery.js:2941)
```

<img width="1440" alt="screen shot 2018-08-08 at 8 04 48 pm" src="https://user-images.githubusercontent.com/13268256/43875706-5665ecb8-9b46-11e8-9b9b-e6007a38ebb6.png">

**Comment by pauljickling** [comment]
The 5465 port is for the old "web" component which is now deprecated.
