### ISSUE TITLE
Perform an npm audit. Upgrade to the latest.

### ISSUE THREAD

**Issue by jpitts** [designforsf/brigade-matchmaker#84]
https://docs.npmjs.com/getting-started/running-a-security-audit

**Comment by jpitts** [comment]
This requires creating a new branch from dev. 

In this branch, an audit will be performed, a new version of npm may be required in order to ease the updating of the package.json files. 

There is a decision point where the ideal version of nodejs is determined (given the upgrades to modules suggested by npm audit). 

Once the upgrade is complete, documentation needs to be updated to reflect the version of nodejs used.

**Comment by pauljickling** [comment]
Completed. I also updated to npm version 6.4.1 so I will start updating docs to reflect that.
